name: Test Google Credentials Secret

on: [ push ]

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if GOOGLE_CREDENTIALS is set
        run: echo "Secret is set" && [ ! -z "$GOOGLE_CREDENTIALS" ]
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}